version: "3.5"

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: gourmandishdb
    ports:
      - 27017:27017
  web:
    image: gourmandish
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: root
      MONGO_PORT: 27017
      MONGO_PW: root
    ports:
      - 3000:3000
#docker-compose up -d

#mongo --u
#pass: root
